name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: [ ubuntu-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v2

      - name: Build the package
        run: conan create . dbus/1.13.18@frederikvannoote/stable -s build_type=Release
